// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0
// source: master_hotel/master_hotel.proto

package master_hotel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestinationAutoComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityCode   string `protobuf:"bytes,1,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	NationName string `protobuf:"bytes,3,opt,name=nation_name,json=nationName,proto3" json:"nation_name,omitempty"`
}

func (x *DestinationAutoComplete) Reset() {
	*x = DestinationAutoComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_hotel_master_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestinationAutoComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationAutoComplete) ProtoMessage() {}

func (x *DestinationAutoComplete) ProtoReflect() protoreflect.Message {
	mi := &file_master_hotel_master_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationAutoComplete.ProtoReflect.Descriptor instead.
func (*DestinationAutoComplete) Descriptor() ([]byte, []int) {
	return file_master_hotel_master_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *DestinationAutoComplete) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *DestinationAutoComplete) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *DestinationAutoComplete) GetNationName() string {
	if x != nil {
		return x.NationName
	}
	return ""
}

type AreaAutoComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NationName string `protobuf:"bytes,1,opt,name=nation_name,json=nationName,proto3" json:"nation_name,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	AreaName   string `protobuf:"bytes,3,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	AreaCode   string `protobuf:"bytes,4,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
}

func (x *AreaAutoComplete) Reset() {
	*x = AreaAutoComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_hotel_master_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaAutoComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaAutoComplete) ProtoMessage() {}

func (x *AreaAutoComplete) ProtoReflect() protoreflect.Message {
	mi := &file_master_hotel_master_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaAutoComplete.ProtoReflect.Descriptor instead.
func (*AreaAutoComplete) Descriptor() ([]byte, []int) {
	return file_master_hotel_master_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *AreaAutoComplete) GetNationName() string {
	if x != nil {
		return x.NationName
	}
	return ""
}

func (x *AreaAutoComplete) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *AreaAutoComplete) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *AreaAutoComplete) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

type HotelAutoComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NationName string `protobuf:"bytes,1,opt,name=nation_name,json=nationName,proto3" json:"nation_name,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	AreaName   string `protobuf:"bytes,3,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	HotelName  string `protobuf:"bytes,4,opt,name=hotel_name,json=hotelName,proto3" json:"hotel_name,omitempty"`
	HotelType  string `protobuf:"bytes,5,opt,name=hotel_type,json=hotelType,proto3" json:"hotel_type,omitempty"`
	HotelCode  string `protobuf:"bytes,6,opt,name=hotel_code,json=hotelCode,proto3" json:"hotel_code,omitempty"`
}

func (x *HotelAutoComplete) Reset() {
	*x = HotelAutoComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_hotel_master_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotelAutoComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelAutoComplete) ProtoMessage() {}

func (x *HotelAutoComplete) ProtoReflect() protoreflect.Message {
	mi := &file_master_hotel_master_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelAutoComplete.ProtoReflect.Descriptor instead.
func (*HotelAutoComplete) Descriptor() ([]byte, []int) {
	return file_master_hotel_master_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *HotelAutoComplete) GetNationName() string {
	if x != nil {
		return x.NationName
	}
	return ""
}

func (x *HotelAutoComplete) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *HotelAutoComplete) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *HotelAutoComplete) GetHotelName() string {
	if x != nil {
		return x.HotelName
	}
	return ""
}

func (x *HotelAutoComplete) GetHotelType() string {
	if x != nil {
		return x.HotelType
	}
	return ""
}

func (x *HotelAutoComplete) GetHotelCode() string {
	if x != nil {
		return x.HotelCode
	}
	return ""
}

type AutoComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []*DestinationAutoComplete `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	Areas  []*AreaAutoComplete        `protobuf:"bytes,2,rep,name=areas,proto3" json:"areas,omitempty"`
	Hotels []*HotelAutoComplete       `protobuf:"bytes,3,rep,name=hotels,proto3" json:"hotels,omitempty"`
}

func (x *AutoComplete) Reset() {
	*x = AutoComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_hotel_master_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoComplete) ProtoMessage() {}

func (x *AutoComplete) ProtoReflect() protoreflect.Message {
	mi := &file_master_hotel_master_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoComplete.ProtoReflect.Descriptor instead.
func (*AutoComplete) Descriptor() ([]byte, []int) {
	return file_master_hotel_master_hotel_proto_rawDescGZIP(), []int{3}
}

func (x *AutoComplete) GetCities() []*DestinationAutoComplete {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *AutoComplete) GetAreas() []*AreaAutoComplete {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *AutoComplete) GetHotels() []*HotelAutoComplete {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type AutoCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit   int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *AutoCompleteRequest) Reset() {
	*x = AutoCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_master_hotel_master_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompleteRequest) ProtoMessage() {}

func (x *AutoCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_hotel_master_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompleteRequest.ProtoReflect.Descriptor instead.
func (*AutoCompleteRequest) Descriptor() ([]byte, []int) {
	return file_master_hotel_master_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *AutoCompleteRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AutoCompleteRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_master_hotel_master_hotel_proto protoreflect.FileDescriptor

var file_master_hotel_master_hotel_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x18, 0x70, 0x6f, 0x73, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x74, 0x0a, 0x17, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x41, 0x72, 0x65, 0x61, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xcb,
	0x01, 0x0a, 0x11, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xe0, 0x01, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x49, 0x0a,
	0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x70, 0x6f, 0x73, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74,
	0x65, 0x6c, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x12, 0x43, 0x0a, 0x06, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x6f, 0x73,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x41, 0x75, 0x74, 0x6f, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x06, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x22,
	0x45, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0x79, 0x0a, 0x0b, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x6a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x6f,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2d, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x6f, 0x73, 0x2e, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x74,
	0x65, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x22,
	0x00, 0x42, 0x31, 0x5a, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x63, 0x68, 0x61, 0x6b, 0x72, 0x61,
	0x2e, 0x75, 0x6e, 0x6f, 0x2f, 0x63, 0x72, 0x6d, 0x2f, 0x70, 0x6f, 0x73, 0x2e, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_master_hotel_master_hotel_proto_rawDescOnce sync.Once
	file_master_hotel_master_hotel_proto_rawDescData = file_master_hotel_master_hotel_proto_rawDesc
)

func file_master_hotel_master_hotel_proto_rawDescGZIP() []byte {
	file_master_hotel_master_hotel_proto_rawDescOnce.Do(func() {
		file_master_hotel_master_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_master_hotel_master_hotel_proto_rawDescData)
	})
	return file_master_hotel_master_hotel_proto_rawDescData
}

var file_master_hotel_master_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_master_hotel_master_hotel_proto_goTypes = []interface{}{
	(*DestinationAutoComplete)(nil), // 0: pos.library.master_hotel.DestinationAutoComplete
	(*AreaAutoComplete)(nil),        // 1: pos.library.master_hotel.AreaAutoComplete
	(*HotelAutoComplete)(nil),       // 2: pos.library.master_hotel.HotelAutoComplete
	(*AutoComplete)(nil),            // 3: pos.library.master_hotel.AutoComplete
	(*AutoCompleteRequest)(nil),     // 4: pos.library.master_hotel.AutoCompleteRequest
}
var file_master_hotel_master_hotel_proto_depIdxs = []int32{
	0, // 0: pos.library.master_hotel.AutoComplete.cities:type_name -> pos.library.master_hotel.DestinationAutoComplete
	1, // 1: pos.library.master_hotel.AutoComplete.areas:type_name -> pos.library.master_hotel.AreaAutoComplete
	2, // 2: pos.library.master_hotel.AutoComplete.hotels:type_name -> pos.library.master_hotel.HotelAutoComplete
	4, // 3: pos.library.master_hotel.MasterHotel.GetAutoComplete:input_type -> pos.library.master_hotel.AutoCompleteRequest
	3, // 4: pos.library.master_hotel.MasterHotel.GetAutoComplete:output_type -> pos.library.master_hotel.AutoComplete
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_master_hotel_master_hotel_proto_init() }
func file_master_hotel_master_hotel_proto_init() {
	if File_master_hotel_master_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_master_hotel_master_hotel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestinationAutoComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_master_hotel_master_hotel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaAutoComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_master_hotel_master_hotel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotelAutoComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_master_hotel_master_hotel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_master_hotel_master_hotel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_master_hotel_master_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_hotel_master_hotel_proto_goTypes,
		DependencyIndexes: file_master_hotel_master_hotel_proto_depIdxs,
		MessageInfos:      file_master_hotel_master_hotel_proto_msgTypes,
	}.Build()
	File_master_hotel_master_hotel_proto = out.File
	file_master_hotel_master_hotel_proto_rawDesc = nil
	file_master_hotel_master_hotel_proto_goTypes = nil
	file_master_hotel_master_hotel_proto_depIdxs = nil
}
